spec_builder_ui <- function(
    data_path = NULL,
    spec_path = NULL,
    study_id = NULL,
    generated_by = Sys.info()[["user"]]
) {
  shiny::fluidPage(
    shiny::titlePanel("📘 Raw Data Spec Builder"),
    
    shiny::sidebarLayout(
      shiny::sidebarPanel(
        width = 3,
        # --- Study Info ---
        shiny::textInput("study_id", "Study ID:", value = study_id %||% ""),
        shiny::textInput("generated_by", "Generated by:", value = generated_by),
        shiny::textInput("data_path", "Raw Data Path:", value = data_path %||% ""),
        shiny::textInput("spec_path", "Existing Spec Path (optional):", value = spec_path %||% ""),
        shiny::actionButton("load_data", "📂 Load Datasets"),
        shiny::hr(),
        shiny::downloadButton("download_spec", "📤 Generate Spec")
      ),
      
      shiny::mainPanel(
        width = 9,
        shiny::tabsetPanel(id = "tabs",
                           shiny::tabPanel("Dataset Overview", DT::dataTableOutput("dataset_overview")),
                           shiny::tabPanel("Data Info", DT::dataTableOutput("data_info_table")),
                           shiny::tabPanel("Checkpoints", DT::dataTableOutput("checkpoints_table")),
                           shiny::tabPanel("Preview Spec", shiny::verbatimTextOutput("preview_spec"))
        )
      )
    ),
    
    shiny::tags$footer(
      shiny::tags$hr(),
      shiny::p("rchk0 · Spec Builder v1.0.0 | Last updated ", Sys.Date(),
               style = "text-align:center; color:#888; font-size:12px;")
    )
  )
}
