spec_builder_ui <- function(
    data_path = DATA_PATH,
    spec_path = SPEC_PATH,
    study_id = STUDY_NAME,
    generated_by = Sys.info()[["user"]]
) {
  shiny::fluidPage(
    shiny::titlePanel("📘 Raw Data Spec Builder"),
    
    shiny::sidebarLayout(
      shiny::sidebarPanel(
        width = 3,
        # --- Study Info ---
        shiny::textInput("study_id", "Study ID:", value = study_id %||% ""),
        shiny::textInput("generated_by", "Generated by:", value = generated_by),
        shiny::textInput("data_path", "Raw Data Path:", value = data_path %||% ""),
        shiny::textInput("exclude_prefixes", "Exclude prefixes (comma separated):", 
                  value = "sys, cdms"),
        shiny::textInput("exclude_names", "Exclude exact names (comma separated):", 
                  value = "record_count, rtsm_sbjct_data"),
        shiny::textInput("spec_path", "Existing Spec Path (optional):", value = spec_path %||% ""),
        shiny::actionButton("load_data", "📂 Load Datasets"),
        shiny::hr(),
        shiny::actionButton("generate_spec", "Generate Spec"),
        shiny::downloadButton("download_spec", "Download Spec")
      ),
      
      shiny::mainPanel(
        width = 9,
        shiny::tabsetPanel(id = "tabs",
                           shiny::tabPanel(
                             "Dataset Summary",
                             DT::DTOutput("dataset_summary", width = "100%", height = "600px")
                           ),
                           tabPanel("Visit Info", dataTableOutput("visit_info")),
                           tabPanel("Checkpoints", dataTableOutput("checkpoints_registry"))
        )
      )
    ),
    
    shiny::tags$footer(
      shiny::tags$hr(),
      shiny::p("rchk0 · Spec Builder v1.0.0 | Last updated ", Sys.Date(),
               style = "text-align:center; color:#888; font-size:12px;")
    )
  )
}
