#' Generate spec workbook (and optional YAML) for raw-data checks
#'
#' @param config list. Required fields: study_id, generated_by.
#'   Optional fields: visit_info_df (data.frame), checkpoints_enabled (data.frame), datasets_pool (list).
#' @param path character. Output .xlsx path.
#' @param include_yaml logical. If TRUE, also write a YAML spec next to the Excel.
#' @param yaml_path character. Optional YAML path. If NULL and include_yaml=TRUE, auto-derive from `path`.
#'
#' @return (invisible) path (xlsx path)
#' @export
generate_spec <- function(config,
                          path,
                          include_yaml = FALSE,
                          yaml_path = NULL) {
  # -------- 0) Validate inputs --------
  stopifnot(is.list(config))
  req_chr <- function(x, nm) {
    if (is.null(x) || !is.character(x) || length(x) != 1 || !nzchar(x)) {
      stop(sprintf("`%s` must be a non-empty character(1).", nm), call. = FALSE)
    }
  }
  
  req_chr(config$study_id, "config$study_id")
  req_chr(config$generated_by, "config$generated_by")
  
  if (is.null(path) || !is.character(path) || length(path) != 1) {
    stop("`path` must be character(1).", call. = FALSE)
  }
  
  # Optional objects
  visit_info_df <- config$visit_info_df
  if (!is.null(visit_info_df) && !is.data.frame(visit_info_df)) {
    stop("`config$visit_info_df` must be a data.frame if provided.", call. = FALSE)
  }
  
  checkpoints_df <- config$checkpoints_enabled
  if (!is.null(checkpoints_df) && !is.data.frame(checkpoints_df)) {
    stop("`config$checkpoints_enabled` must be a data.frame if provided.", call. = FALSE)
  }
  
  datasets_pool <- config$datasets_pool
  if (!is.null(datasets_pool) && !is.list(datasets_pool)) {
    stop("`config$datasets_pool` must be a list if provided.", call. = FALSE)
  }
  
  # -------- 1) Build data for sheets --------
  # 1.1 README sheet
  tool_version <- tryCatch(as.character(utils::packageVersion("rchk0")), error = function(e) NA_character_)
  cover_tbl <- data.frame(
    Field = c("Study ID", "Generated by", "Generated at", "Tool", "Tool version"),
    Value = c(
      config$study_id,
      config$generated_by,
      format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"),
      "rchk0::generate_spec",
      ifelse(is.na(tool_version), "", tool_version)
    ),
    stringsAsFactors = FALSE
  )
  
  # --- Create workbook and add the README (COVER) sheet
  wb <- openxlsx::createWorkbook()
  openxlsx::addWorksheet(wb, "README")
  
  # Add the title row
  title_text <- "Raw Data Issue Check Specification (version 1.0.1)"
  title_style <- openxlsx::createStyle(
    fontSize = 14,
    textDecoration = "bold",
    halign = "center",
    valign = "center"
  )
  
  openxlsx::writeData(wb, sheet = "README", x = title_text, startRow = 1, startCol = 1)
  openxlsx::mergeCells(wb, sheet = "README", cols = 1:2, rows = 1)
  openxlsx::addStyle(wb, sheet = "README", style = title_style, rows = 1, cols = 1:2, gridExpand = TRUE)
  
  ## write data table
  openxlsx::writeData(wb, sheet = "README", x = cover_tbl, startRow = 2, startCol = 1, colNames = TRUE)
  
  openxlsx::freezePane(wb, "README", firstActiveRow = 4)
  openxlsx::setColWidths(wb, "README", cols = 1:2, widths = c(25, 60))
  
  
  # 1.2 PREPROCESSING sheet
  preprocessing_cols <- c(
    "DATASET", "SUBJECT_VAR", "SITE_VAR",
    "VISIT_DATE_COL", "VISIT_LABEL_COL",
    "EXCLUDE_ROWS", "EXCLUDE_COLS", "REMOVE"
  )
  if (!is.null(visit_info_df) && nrow(visit_info_df) > 0) {
    map_name <- function(nm) {
      if (nm %in% names(visit_info_df)) nm else NA_character_
    }
    ds_col   <- map_name("dataset")
    sub_col  <- map_name("subject_var")
    site_col <- map_name("site_var")
    vdt_col  <- map_name("visit_date_col")
    vlb_col  <- map_name("visit_label_col")
    
    preproc_tbl <- data.frame(
      DATASET        = if (!is.na(ds_col))   visit_info_df[[ds_col]]   else NA_character_,
      SUBJECT_VAR    = if (!is.na(sub_col))  visit_info_df[[sub_col]]  else NA_character_,
      SITE_VAR       = if (!is.na(site_col)) visit_info_df[[site_col]] else NA_character_,
      VISIT_DATE_COL = if (!is.na(vdt_col))  visit_info_df[[vdt_col]]  else NA_character_,
      VISIT_LABEL_COL= if (!is.na(vlb_col))  visit_info_df[[vlb_col]]  else NA_character_,
      EXCLUDE_ROWS   = NA_character_,
      EXCLUDE_COLS   = NA_character_,
      REMOVE         = NA_character_,
      stringsAsFactors = FALSE
    )
    names(preproc_tbl) <- preprocessing_cols
  } else {
    preproc_tbl <- as.data.frame(
      matrix(nrow = 0, ncol = length(preprocessing_cols)),
      stringsAsFactors = FALSE
    )
    names(preproc_tbl) <- preprocessing_cols
  }
  
  # 1.3 CHECKPOINTS sheet
  checkpoints_tbl <- if (is.null(checkpoints_df)) {
    data.frame(
      checkpoint_id   = character(),
      checkpoint_name = character(),
      enabled         = logical(),
      notes           = character(),
      stringsAsFactors = FALSE
    )
  } else {
    if ("enabled" %in% names(checkpoints_df)) {
      checkpoints_df$enabled <- as.logical(checkpoints_df$enabled)
    }
    checkpoints_df
  }
  
  # 1.4 DATASETS summary sheet
  datasets_tbl <- if (is.null(datasets_pool)) {
    data.frame(
      dataset = character(),
      nrow = integer(),
      ncol = integer(),
      columns = character(),
      stringsAsFactors = FALSE
    )
  } else {
    ds_names <- names(datasets_pool)
    if (is.null(ds_names)) ds_names <- paste0("ds", seq_along(datasets_pool))
    rows <- vapply(datasets_pool, function(x) if (is.data.frame(x)) nrow(x) else NA_integer_, integer(1))
    cols <- vapply(datasets_pool, function(x) if (is.data.frame(x)) ncol(x) else NA_integer_, integer(1))
    coln <- vapply(datasets_pool, function(x) if (is.data.frame(x)) paste(names(x), collapse = ", ") else "", character(1))
    
    data.frame(
      dataset = ds_names,
      nrow = rows,
      ncol = cols,
      columns = coln,
      stringsAsFactors = FALSE
    )
  }
  
  # -------- 2) Write Excel --------
  add_sheet <- function(name, df) {
    openxlsx::addWorksheet(wb, name)
    openxlsx::writeData(wb, name, df)
    openxlsx::freezePane(wb, name, firstRow = TRUE)
    widths <- pmin(pmax(nchar(names(df)) * 1.2, 10), 80)
    openxlsx::setColWidths(wb, name, cols = seq_along(df), widths = widths)
  }
  
  add_sheet("PREPROCESSING", preproc_tbl)
  add_sheet("CHECKPOINTS", checkpoints_tbl)
  add_sheet("DATASETS", datasets_tbl)
  
  header_style  <- openxlsx::createStyle(
    halign = "center",
    textDecoration = "bold",
    fgFill = "#D9E1F2", 
    fontSize = 11
  )
  
  content_style <- openxlsx::createStyle(
    halign = "center",
    valign = "center",
    wrapText = TRUE
  )
  
  # Apply styles and basic formatting for each sheet
  all_sheets <- names(wb)
  
  for (sheet in all_sheets) {

    df <- openxlsx::readWorkbook(wb, sheet = sheet)
    n_rows <- nrow(df)
    n_cols <- ncol(df)
    
    # Skip empty sheets
    if (n_cols == 0) next
    
    # Freeze top row
    if (sheet != "README") {
      openxlsx::freezePane(wb, sheet = sheet, firstRow = TRUE)
    }
    
    # Auto-adjust width (limit between 10 and 50)
    max_char <- sapply(df, function(col) max(nchar(as.character(col)), na.rm = TRUE))
    title_char <- nchar(colnames(df))
    est_width <- pmax(title_char, max_char)
    est_width <- pmin(est_width + 2, 50)
    openxlsx::setColWidths(wb, sheet, cols = 1:n_cols, widths = est_width)
    
    # Add header + content styles
    if (sheet != "README"){
      openxlsx::addStyle(wb, sheet, header_style, rows = 1, cols = 1:n_cols, gridExpand = TRUE)
    }
    else if (sheet == "README"){
      openxlsx::addStyle(wb, sheet, header_style, rows = 2, cols = 1:n_cols, gridExpand = TRUE)
    }

    if (n_rows > 0 & sheet != "README") {
      openxlsx::addStyle(wb, sheet, content_style, rows = 2:(n_rows + 1), cols = 1:n_cols, gridExpand = TRUE)
    } else if (n_rows > 0 & sheet == "README"){
      openxlsx::addStyle(wb, sheet, content_style, rows = 3:(n_rows + 1), cols = 1:n_cols, gridExpand = TRUE)
    }
    
    # Add filters to all columns
    if (sheet != "README"){
      openxlsx::addFilter(wb, sheet, rows = 1, cols = 1:n_cols)
    }
  }
  
  # Save workbook
  dir.create(dirname(path), showWarnings = FALSE, recursive = TRUE)
  openxlsx::saveWorkbook(wb, file = path, overwrite = TRUE)
  
  # -------- 3) Optional YAML --------
  if (isTRUE(include_yaml)) {
    if (is.null(yaml_path)) {
      yaml_path <- sub("\\.xlsx$", ".yml", path, ignore.case = TRUE)
      if (identical(yaml_path, path)) {
        yaml_path <- paste0(path, ".yml")
      }
    }
    yaml_list <- list(
      study = list(
        id = config$study_id,
        generated_by = config$generated_by,
        generated_at = format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"),
        tool = "rchk0::generate_spec",
        tool_version = tool_version
      ),
      preprocessing = preproc_tbl,
      checkpoints = checkpoints_tbl
    )
    
    if (!requireNamespace("yaml", quietly = TRUE)) {
      warning("Package `yaml` not installed; YAML will not be written.")
    } else {
      yaml_txt <- yaml::as.yaml(yaml_list, line.sep = "\n")
      writeLines(yaml_txt, con = yaml_path, useBytes = TRUE)
    }
  }
  
  message("✅ Spec written to: ", normalizePath(path, winslash = "/"))
  if (isTRUE(include_yaml)) {
    message("✅ YAML written to: ", normalizePath(yaml_path, winslash = "/"))
  }
  invisible(path)
}
